# The Docker image that will be used to build your app
image: leanprovercommunity/lean:debian
create-pages:
  pages: true
    # The folder that contains the files to be exposed at the Page URL
    # publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  run:
    - name: 'build_project'
      script: lake update && lake build
    - name: 'build_docs'
      script: cd docbuild; make build
